name: Excersice 2
on: push
jobs:

  markdownlint-cli:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
      - uses: nosborn/github-action-markdown-cli@v3.5.0
        with:
          files: .
          config_file: .markdownlint.yaml
          dot: true
          ignore_files: examples/ignore/*
          ignore_path: examples/.markdownlintignore
          rules: examples/rules/custom.js
          
#  editorconfig:
 #   runs-on: ubuntu-latest
  #  steps:
   #   - uses: actions/checkout@v4
    #  - uses: editorconfig-checker/action-editorconfig-checker@main
     # - run: editorconfig-checker
      
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh      
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Artifact # Name of the step
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
          name: code
          path: .
          include-hidden-files: true
  Linting:
    needs: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Artifact # Name of the step
        uses: actions/download-artifact@v4 # Action to use
        with: # Parameters for the action
          name: code # Name of the artifact to download. Optional. If unspecified, all artifacts for the run are downloaded.
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v7 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
